### ISSUE TITLE
For v1.0 some methods of FrozenColor are broken

### ISSUE THREAD

**Issue by ak64th** [HexDecimal/libtcod-cffi#11]
For v1.0 some methods of tcod.FrozenColor are broken. For example `tcod.darkest_blue * 3` will raise a TypeError since `FrozenColor.__mul__` is an unbound method of `Color`. I think it can be fixed by replace `__mul__ = Color.__mul_` with `__mul__ = Color.__mul__.__func__` in __init__.py

I see FrozenColor has been removed in v2 but would you like to create something like v1.0.1?

**Comment by HexDecimal** [comment]
Looks like bug only affects Python 2.

The proper solution would've been to use a mix-in, or to create the functions outside of the classes before assigning them as methods.

libtcod-cffi is a little hard to deploy and deployment has changed in a alpha versions.  I don't know much effort it will take to make a v1.0.1 release.  It'll probably be easier for me to just rush the v2.0 release.

**Comment by HexDecimal** [comment]
I've pushed the v2.0.0 release.  I've specifically tested for this issue and it looks OK.
