### ISSUE TITLE
Enhancement Request:  Better search for LIBTCOD_DLL_PATH

### ISSUE THREAD

**Issue by brianbruggeman** [HexDecimal/libtcod-cffi#17]
Notably, I'm on a mac.

I wrote this code, and I now preface it before I import `tcod`:

    def setup_tcod_shared_object_paths():
        dll_path_to_search = [
            os.path.abspath(os.getcwd()),
            os.path.dirname(__file__),
        ]

        if sys.platform in ['darwin', 'linux']:
            dll_path_to_search.extend([
                '~/lib',
                '~/.local/lib',
                '/usr/local/lib',
                '/usr/lib',
            ])
        elif sys.platform in ['win32']:
            dll_path_to_search.extend([
                '\\Windows\\System32',
                '\\Windows',
            ])

        if 'LIBTCOD_DLL_PATH' not in os.environ:
            os.environ['LIBTCOD_DLL_PATH'] = ';'.join(dll_path_to_search)
        else:
            dll_path = os.environ.get('LIBTCOD_DLL_PATH')
            dll_path = ';'.join((dll_path, ';'.join(dll_path_to_search)))

    setup_tcod_shared_object_paths()
    import tcod  # noqa

It would maybe be nice if we added something like this to tcod here:  https://github.com/HexDecimal/libtcod-cffi/blob/master/tcod/__init__.py#L19

It won't catch all cases, but it would lower the barrier for many new people.

**Comment by HexDecimal** [comment]
libtcod-cffi statically links to the libtcod library.  So any external version of libtcod is currently ignored.  Because libtcod-cffi uses internal libtcod headers, and because this method side-steps all libtcod specific linking issues on all platforms, this will probably not be changed.

The hard part is that the SDL2 library still needs to be dynamically linked.  Your previous issue implied that MacOS checked the system libraries before using the version of SDL2 bundled with libtcod-cffi, which caused an issue since your system installed SDL2 was out-of-date at the time.  I'm not sure how to go about fixing that.

**Comment by brianbruggeman** [comment]
It definitely helps to understand how you designed the code.  

The reason I wanted to go with `libtcod-cffi` is because I can put that into my list of requirements within my setup.py file for my games.  `libtcodpy` is not something I can install from pypi or have as a basic requirement if I want to run a `pip install <game>`.  I didn't notice that was a problem until I wanted to start testing things through a continuous integration point of view.  I ended up installing `libtcod-cffi` within a virtual environment that had already installed `libtcodpy` using scons and pip from a cloned libtcod mercurial repo.  

So my failures and subsequent work-arounds are likely from the assumption that a cffi-based library will be okay with my system level package.  I haven't looked into the installation pathway for `libtcod-cffi`, but I suspect my issues are related to the installation order I used.

**Comment by HexDecimal** [comment]
There shouldn't be any issues with installing libtcod-cffi and libtcodpy in the same virtual environment.  I have both installed on my Windows system.  I also made libtcod's SCons builder, which sets up linking with SDL2 similar to how libtcod-cffi is setup.  It'd be weird if libtcod-cffi is having problems that don't show up in libtcodpy also.

Is there anywhere I can view one of your failed continuous integration logs?

**Comment by HexDecimal** [comment]
I've uploaded a new version `v2.2.1` which should be more zealous when it comes to linking with the bundled SDL2 library.  I'm hoping this will fix the issues you've been having.

**Comment by brianbruggeman** [comment]
Now that 7drl is over, I can go back and check a few things out....  I'll take a look.  Thank you!
