### ISSUE TITLE
Unable to install Python 3.4, Debian Wheezy error: conflicting types for ‘uintptr_t’

### ISSUE THREAD

**Issue by mkesper** [HexDecimal/libtcod-cffi#3]
```Python traceback
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Itcod/include/libtcod-1.5 -Itcod/include/SDL-1.2 -IRelease/tcod/ -I/usr/include/python3.4m -I/home/michael/src/mylarn/python/include/python3.4m -c build/temp.linux-i686-3.4/tcod._libtcod_cp34.c -o build/temp.linux-i686-3.4/build/temp.linux-i686-3.4/tcod._libtcod_cp34.o
In file included from tcod/include/SDL-1.2/SDL_config.h:42:0,
                 from tcod/include/SDL-1.2/SDL_stdinc.h:30,
                 from tcod/include/SDL-1.2/SDL_main.h:26,
                 from tcod/include/SDL-1.2/SDL.h:30,
                 from build/temp.linux-i686-3.4/tcod._libtcod_cp34.c:394:
tcod/include/SDL-1.2/SDL_config_minimal.h:39:23: error: conflicting types for ‘uintptr_t’
 typedef unsigned long uintptr_t;
                       ^
In file included from /usr/lib/gcc/i586-linux-gnu/4.9/include/stdint.h:9:0,
                 from /usr/include/inttypes.h:27,
                 from /usr/include/python3.4m/pyport.h:9,
                 from /usr/include/python3.4m/Python.h:50,
                 from build/temp.linux-i686-3.4/tcod._libtcod_cp34.c:2:
/usr/include/stdint.h:128:23: note: previous declaration of ‘uintptr_t’ was here
 typedef unsigned int  uintptr_t;
                       ^
´´´

**Comment by mkesper** [comment]
Unable to upload full log, sorry.

**Comment by HexDecimal** [comment]
Looks like an incompatibility between the included SDL code and your native "/usr/include/stdint.h" file.  I wonder if the headers for SDL on Debian are modified from the original.

Tell me if this works:
- Make sure you have the source files: https://github.com/HexDecimal/libtcod-cffi/releases
- In the source, delete the directory "SDL-1.2" from "libtcod-cffi/tcod/include/"
- Install the Debian source package for SDL, should be something like: "libsdl1.2-dev"
- Try to install from the source, the command is probably "python34 setup.py install"

And then get back to me.  I'll look into making the compiler prefer system include directories over my included headers.

**Comment by mkesper** [comment]
After installing libsdl1.2-dev, I had to symlink SDL1.2 to /usr/include/SDL and was able to build with some warnings about function declarations not being prototypes etc.
Thanks!

**Comment by HexDecimal** [comment]
Thanks for confirming that the distribution dev files work.  I should have asked you if you could get it to install from master as it's using the "-idirafter" linking flag right now.

I'm going to resume work on this.  I need to make sure that it prefers the Linux distro's dev files over the ones provided by the Python package.

If I can't confirm it myself then I might ask you to see if the next release works out of the box.

**Comment by mkesper** [comment]
Hi Kyle,

Am 20.10.2015 um 22:07 schrieb Kyle Stewart:

> Thanks for confirming that the distribution dev files work. I should
> have asked you if you could get it to install from master as it's using
> the "-idirafter" linking flag right now.

I have seen that only after getting so far. ;)
That option doesn't have the desired effect, though.
Tested with a fresh virtualenv and from git and it comes to the same error.

Bye
Michael

**Comment by HexDecimal** [comment]
I was able to fix this error, but not a error that comes up when using an outdated version of cffi.  Pip refuses to update modules in order, so you'll always have to upgrade the install of cffi before installing libtcod-cffi.
