### ISSUE TITLE
map_compute_fov Ignores Radius

### ISSUE THREAD

**Issue by seancallaway** [HexDecimal/libtcod-cffi#6]
Hello,

Calls to the `map_compute_fov()` function seem to ignore the radius parameter and light only a 3x3 square centered on the player. Even passing `0` (which the [documentation](http://roguecentral.org/doryen/data/libtcod/doc/1.5.1/html2/fov_compute.html?c=false&cpp=false&cs=false&py=false&lua=false) says should make the range unlimited) does not work. 

I don't know if it's related to the same 1.6 issue mentioned [here](http://roguecentral.org/doryen/forum/index.php?topic=1669.0).

Any help would be appreciated.

Python: 2.7.12
cffi: 1.7.0
libtcod-cffi: 0.2.8

**Comment by HexDecimal** [comment]
Have you touched the maps transparency properties yet?  The maps are opaque by default, which would cause the effect you described.

**Comment by seancallaway** [comment]
The fov_map is initialized with the following:

`libtcod.map_set_properties(self.fov_map, x, y, not self.map[x][y].block_sight, not self.map[x][y].blocked)`

Per the tutorial, only walls have `block_sight` and `blocked` set to True.

**Comment by HexDecimal** [comment]
I took the [FOV tutorial here](http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod,_part_4_code#Exploration), changing libtcodpy to tcod, and set TORCH_RADIUS to 0.
Resulting in this example code: [fov_example.zip](https://github.com/HexDecimal/libtcod-cffi/files/446502/fov_example.zip)

This example worked correctly when I ran it.

**Comment by seancallaway** [comment]
I figured out what it was. Had to do with the placement of the `libtcod.map_set_properties()` call. I'm sorry for wasting your time, but greatly appreciate your response.
